export const blogMagazineConfig = {
  id: 'blog-magazine',
  name: 'Tech Insights',
  tagline: 'De Laatste Ontwikkelingen in Technologie',
  description: 'Professional blog platform met artikelen, categorieën, auteurs en zoekfunctie',
  type: 'multi-page' as const,

  // Branding
  colors: {
    primary: '#2563EB',
    primaryHover: '#1D4ED8',
    accent: '#7C3AED',
  },

  // Categories
  categories: [
    { id: 'all', name: 'Alles', icon: '📰', color: 'bg-gray-600' },
    { id: 'tech', name: 'Technologie', icon: '💻', color: 'bg-blue-600' },
    { id: 'ai', name: 'AI & ML', icon: '🤖', color: 'bg-purple-600' },
    { id: 'web', name: 'Web Development', icon: '🌐', color: 'bg-green-600' },
    { id: 'mobile', name: 'Mobile', icon: '📱', color: 'bg-pink-600' },
    { id: 'cloud', name: 'Cloud', icon: '☁️', color: 'bg-cyan-600' },
    { id: 'security', name: 'Security', icon: '🔒', color: 'bg-red-600' },
  ],

  // Articles
  articles: [
    {
      id: '1',
      title: 'De Toekomst van AI in 2024: Wat Kunnen We Verwachten?',
      slug: 'de-toekomst-van-ai-2024',
      excerpt: 'Kunstmatige intelligentie ontwikkelt zich razendsnel. In dit artikel onderzoeken we de belangrijkste trends en ontwikkelingen die we in 2024 kunnen verwachten.',
      content: 'Volledige artikel content hier...',
      category: 'ai',
      author: {
        name: 'Dr. Lisa van Dam',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
        bio: 'AI Researcher & Tech Writer',
      },
      image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-15',
      readTime: 8,
      views: 15234,
      likes: 892,
      featured: true,
      tags: ['AI', 'Machine Learning', 'Future Tech'],
    },
    {
      id: '2',
      title: 'React Server Components: Een Revolutie in Web Development',
      slug: 'react-server-components-revolutie',
      excerpt: 'Server Components veranderen de manier waarop we React applicaties bouwen. Ontdek de voordelen en best practices.',
      content: 'Volledige artikel content hier...',
      category: 'web',
      author: {
        name: 'Mark Jansen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
        bio: 'Full Stack Developer',
      },
      image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-12',
      readTime: 12,
      views: 8932,
      likes: 543,
      featured: true,
      tags: ['React', 'Web Development', 'JavaScript'],
    },
    {
      id: '3',
      title: 'Cloud Security Best Practices voor 2024',
      slug: 'cloud-security-best-practices-2024',
      excerpt: 'Beveilig je cloud infrastructuur met deze essentiële security practices en tools.',
      content: 'Volledige artikel content hier...',
      category: 'security',
      author: {
        name: 'Sophie Martens',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
        bio: 'Security Specialist',
      },
      image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-10',
      readTime: 10,
      views: 6721,
      likes: 421,
      tags: ['Security', 'Cloud', 'Best Practices'],
    },
    {
      id: '4',
      title: 'Flutter vs React Native: Welke Kies Je in 2024?',
      slug: 'flutter-vs-react-native-2024',
      excerpt: 'Een gedetailleerde vergelijking van de twee meest populaire cross-platform frameworks.',
      content: 'Volledige artikel content hier...',
      category: 'mobile',
      author: {
        name: 'Tom de Vries',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
        bio: 'Mobile Developer',
      },
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-08',
      readTime: 15,
      views: 11245,
      likes: 678,
      featured: true,
      tags: ['Flutter', 'React Native', 'Mobile Development'],
    },
    {
      id: '5',
      title: 'Microservices Architectuur: Wanneer Wel en Niet?',
      slug: 'microservices-architectuur-wanneer',
      excerpt: 'Microservices zijn niet altijd de oplossing. Leer wanneer deze architectuur zinvol is.',
      content: 'Volledige artikel content hier...',
      category: 'cloud',
      author: {
        name: 'Dr. Lisa van Dam',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
        bio: 'AI Researcher & Tech Writer',
      },
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-05',
      readTime: 11,
      views: 9134,
      likes: 512,
      tags: ['Microservices', 'Architecture', 'Cloud'],
    },
    {
      id: '6',
      title: 'TypeScript 5.0: Alle Nieuwe Features',
      slug: 'typescript-5-nieuwe-features',
      excerpt: 'TypeScript 5.0 brengt krachtige nieuwe features. Ontdek wat er nieuw is.',
      content: 'Volledige artikel content hier...',
      category: 'web',
      author: {
        name: 'Mark Jansen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
        bio: 'Full Stack Developer',
      },
      image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=1200&h=600&fit=crop',
      publishedAt: '2024-01-03',
      readTime: 9,
      views: 7621,
      likes: 445,
      tags: ['TypeScript', 'JavaScript', 'Programming'],
    },
  ],

  // Trending Topics
  trending: [
    'AI & Machine Learning',
    'Cloud Computing',
    'Web3',
    'Cybersecurity',
    'DevOps',
    'Quantum Computing',
  ],
};

export type BlogMagazineConfig = typeof blogMagazineConfig;
