import { Destination, Package } from './types';

export const travelScapeConfig = {
  name: 'TravelScape',
  tagline: 'Ontdek De Wereld',

  destinations: [
    {
      id: 'bali',
      name: 'Bali',
      country: 'Indonesië',
      description: 'Tropisch paradijs met prachtige stranden, rijstvelden en tempels. Perfect voor ontspanning en avontuur.',
      image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200',
      rating: 4.9,
      reviews: 2847,
      price: 899,
      duration: '8 dagen',
      type: 'beach' as const,
      highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Seminyak Beach', 'Monkey Forest'],
      included: ['Retourvlucht', '7 nachten 4* hotel', 'Ontbijt', 'Airport transfers', 'City tour'],
    },
    {
      id: 'tokyo',
      name: 'Tokyo',
      country: 'Japan',
      description: 'Moderne metropool met perfecte mix van traditie en technologie. Ontdek tempels, neon lights en culinaire hoogstandjes.',
      image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200',
      rating: 4.8,
      reviews: 3421,
      price: 1299,
      duration: '10 dagen',
      type: 'city' as const,
      highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Mount Fuji', 'Robot Restaurant'],
      included: ['Retourvlucht', '9 nachten 4* hotel', 'JR Pass 7 dagen', 'Guided tours', 'Airport transfers'],
    },
    {
      id: 'iceland',
      name: 'Reykjavik',
      country: 'IJsland',
      description: 'Land van vuur en ijs met spectaculaire watervallen, geysers en noorderlicht. Een natuurwonder!',
      image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200',
      rating: 4.9,
      reviews: 1923,
      price: 1199,
      duration: '7 dagen',
      type: 'nature' as const,
      highlights: ['Golden Circle', 'Blue Lagoon', 'Northern Lights', 'Gullfoss Waterfall'],
      included: ['Retourvlucht', '6 nachten accommodatie', '4x4 huurauto', 'Blue Lagoon toegang'],
    },
    {
      id: 'santorini',
      name: 'Santorini',
      country: 'Griekenland',
      description: 'Iconisch Grieks eiland met witte huisjes, blauwe koepels en adembenemende zonsondergangen.',
      image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200',
      rating: 4.9,
      reviews: 4125,
      price: 799,
      duration: '6 dagen',
      type: 'beach' as const,
      highlights: ['Oia Sunset', 'Red Beach', 'Ancient Akrotiri', 'Wine Tasting'],
      included: ['Retourvlucht', '5 nachten hotel', 'Ontbijt', 'Catamaran cruise', 'Airport transfers'],
    },
    {
      id: 'patagonia',
      name: 'Patagonia',
      country: 'Argentinië & Chili',
      description: 'Ongerepte wildernis met gletsjers, bergen en unieke wildlife. Voor de echte avonturier!',
      image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200',
      rating: 4.8,
      reviews: 1532,
      price: 1599,
      duration: '12 dagen',
      type: 'adventure' as const,
      highlights: ['Torres del Paine', 'Perito Moreno Glacier', 'El Chalten', 'Wildlife Safari'],
      included: ['Retourvlucht', '11 nachten accommodatie', 'Gids', 'Alle nationale parken', 'Transfers'],
    },
    {
      id: 'marrakech',
      name: 'Marrakech',
      country: 'Marokko',
      description: 'Exotische stad vol kleuren, geuren en souks. Duik in de Marokkaanse cultuur en gastvrijheid.',
      image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1200',
      rating: 4.7,
      reviews: 2634,
      price: 599,
      duration: '5 dagen',
      type: 'culture' as const,
      highlights: ['Jemaa el-Fnaa', 'Bahia Palace', 'Atlas Mountains', 'Souk Shopping'],
      included: ['Retourvlucht', '4 nachten riad', 'Ontbijt & diner', 'Desert tour', 'Airport transfers'],
    },
  ] as Destination[],

  packages: [
    {
      id: 'pkg-1',
      name: 'Azië Hoogtepunten',
      destination: 'Thailand, Vietnam & Cambodia',
      image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800',
      price: 1899,
      duration: '21 dagen',
      includes: ['Alle vluchten', '20 nachten hotels', 'Dagelijkse tours', 'Ontbijt'],
      departure: '5 Apr 2026',
    },
    {
      id: 'pkg-2',
      name: 'Europese Steden Tour',
      destination: 'Parijs, Rome, Barcelona & Amsterdam',
      image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800',
      price: 1499,
      duration: '14 dagen',
      includes: ['Treinkaarten', '13 nachten hotels', 'Museum passes', 'Ontbijt'],
      departure: '12 Mei 2026',
    },
    {
      id: 'pkg-3',
      name: 'Caribisch Paradijs',
      destination: 'Aruba, Curaçao & Bonaire',
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800',
      price: 1699,
      duration: '10 dagen',
      includes: ['Retourvlucht', '9 nachten resorts', 'All-inclusive', 'Island hopping'],
      departure: '18 Jun 2026',
    },
  ] as Package[],
};
