import { Course, Module } from './types';

export const learnHubConfig = {
  name: 'LearnHub',
  tagline: 'Leer Nieuwe Vaardigheden Online',
  categories: ['Web Development', 'Design', 'Business', 'Marketing', 'Data Science', 'Fotografie'],

  courses: [
    {
      id: 'react-advanced',
      title: 'Advanced React & TypeScript',
      instructor: 'Sarah Johnson',
      instructorImage: 'https://i.pravatar.cc/150?img=1',
      description: 'Master advanced React patterns, hooks, and TypeScript integration. Build production-ready applications.',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800',
      category: 'Web Development',
      level: 'Advanced' as const,
      duration: '12 uur',
      lessons: 48,
      students: 3421,
      rating: 4.8,
      reviews: 892,
      price: 89.99,
      enrolled: true,
      progress: 65,
      tags: ['React', 'TypeScript', 'Hooks', 'Performance'],
    },
    {
      id: 'ui-ux-masterclass',
      title: 'UI/UX Design Masterclass',
      instructor: 'Mike Chen',
      instructorImage: 'https://i.pravatar.cc/150?img=2',
      description: 'Learn professional UI/UX design from scratch. Master Figma, user research, and design systems.',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800',
      category: 'Design',
      level: 'Intermediate' as const,
      duration: '15 uur',
      lessons: 52,
      students: 5120,
      rating: 4.9,
      reviews: 1243,
      price: 79.99,
      enrolled: true,
      progress: 30,
      tags: ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
    },
    {
      id: 'digital-marketing',
      title: 'Complete Digital Marketing',
      instructor: 'Emma Wilson',
      instructorImage: 'https://i.pravatar.cc/150?img=3',
      description: 'Master SEO, social media marketing, email campaigns, and analytics. Grow your online presence.',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800',
      category: 'Marketing',
      level: 'Beginner' as const,
      duration: '10 uur',
      lessons: 38,
      students: 7834,
      rating: 4.7,
      reviews: 2103,
      price: 69.99,
      tags: ['SEO', 'Social Media', 'Email Marketing', 'Analytics'],
    },
    {
      id: 'python-data-science',
      title: 'Python for Data Science',
      instructor: 'David Park',
      instructorImage: 'https://i.pravatar.cc/150?img=4',
      description: 'Learn Python, pandas, numpy, and machine learning. Analyze data and build predictive models.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f0a?auto=format&fit=crop&w=800',
      category: 'Data Science',
      level: 'Intermediate' as const,
      duration: '18 uur',
      lessons: 64,
      students: 4521,
      rating: 4.8,
      reviews: 1567,
      price: 99.99,
      tags: ['Python', 'Pandas', 'Machine Learning', 'Data Analysis'],
    },
    {
      id: 'photography-basics',
      title: 'Photography Fundamentals',
      instructor: 'Lisa Anderson',
      instructorImage: 'https://i.pravatar.cc/150?img=5',
      description: 'Master camera settings, composition, lighting, and post-processing. Take stunning photos.',
      image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=800',
      category: 'Fotografie',
      level: 'Beginner' as const,
      duration: '8 uur',
      lessons: 32,
      students: 6234,
      rating: 4.9,
      reviews: 1876,
      price: 59.99,
      tags: ['Camera', 'Composition', 'Lighting', 'Editing'],
    },
    {
      id: 'business-strategy',
      title: 'Business Strategy & Leadership',
      instructor: 'Robert Martinez',
      instructorImage: 'https://i.pravatar.cc/150?img=6',
      description: 'Develop strategic thinking, leadership skills, and business acumen. Lead successful organizations.',
      image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800',
      category: 'Business',
      level: 'Advanced' as const,
      duration: '14 uur',
      lessons: 45,
      students: 2891,
      rating: 4.7,
      reviews: 734,
      price: 94.99,
      tags: ['Strategy', 'Leadership', 'Management', 'Growth'],
    },
  ] as Course[],

  modules: [
    {
      id: 'mod-1',
      title: 'Getting Started with React Hooks',
      lessons: [
        { id: 'l1', title: 'Introduction to Hooks', duration: '12:34', completed: true, type: 'video' as const },
        { id: 'l2', title: 'useState in Depth', duration: '18:22', completed: true, type: 'video' as const },
        { id: 'l3', title: 'useEffect Mastery', duration: '22:15', completed: true, type: 'video' as const },
        { id: 'l4', title: 'Quiz: Hooks Basics', duration: '10:00', completed: false, type: 'quiz' as const },
      ],
    },
    {
      id: 'mod-2',
      title: 'Advanced Patterns',
      lessons: [
        { id: 'l5', title: 'Custom Hooks', duration: '25:41', completed: false, type: 'video' as const },
        { id: 'l6', title: 'Context API', duration: '19:33', completed: false, type: 'video' as const },
        { id: 'l7', title: 'Performance Optimization', duration: '28:17', completed: false, type: 'video' as const },
        { id: 'l8', title: 'Reading: Best Practices', duration: '15:00', completed: false, type: 'reading' as const },
      ],
    },
    {
      id: 'mod-3',
      title: 'TypeScript Integration',
      lessons: [
        { id: 'l9', title: 'TypeScript Basics', duration: '16:45', completed: false, type: 'video' as const },
        { id: 'l10', title: 'Typing Props & State', duration: '20:12', completed: false, type: 'video' as const },
        { id: 'l11', title: 'Advanced Types', duration: '24:38', completed: false, type: 'video' as const },
        { id: 'l12', title: 'Final Project', duration: '45:00', completed: false, type: 'video' as const },
      ],
    },
  ] as Module[],
};
