import { Car } from './types';

export const autoVaultConfig = {
  name: 'AutoVault',
  tagline: 'Premium Auto Dealership',

  cars: [
    {
      id: 'bmw-m4',
      make: 'BMW',
      model: 'M4 Competition',
      year: 2024,
      price: 89950,
      image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200',
      ],
      type: 'sports' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Benzine' as const,
      color: 'Blauw Metallic',
      doors: 2,
      seats: 4,
      power: '510 PK',
      features: ['Adaptive M Suspension', 'M Sport Exhaust', 'Carbon Fiber Roof', 'Harman Kardon Audio', 'Head-Up Display', 'Adaptive Cruise Control'],
      description: 'De ultieme sportieve rijervaring. Pure BMW M-power met geavanceerde technologie en adembenemende prestaties.',
    },
    {
      id: 'tesla-model-3',
      make: 'Tesla',
      model: 'Model 3 Long Range',
      year: 2024,
      price: 52990,
      image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&w=1200',
      ],
      type: 'electric' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Elektrisch' as const,
      color: 'Wit Parelmoer',
      doors: 4,
      seats: 5,
      power: '351 PK',
      features: ['Autopilot', '614 km bereik', 'Premium Audio', 'Glass Roof', 'Over-the-air updates', 'Supercharging'],
      description: 'De toekomst van rijden. Volledig elektrisch met ongeëvenaarde technologie en comfort.',
    },
    {
      id: 'range-rover',
      make: 'Range Rover',
      model: 'Sport Autobiography',
      year: 2023,
      price: 125900,
      image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200',
      ],
      type: 'luxury' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Hybrid' as const,
      color: 'Zwart Metallic',
      doors: 5,
      seats: 5,
      power: '510 PK',
      features: ['Air Suspension', 'Meridian Sound', '360° Camera', 'Massagestoelen', 'Panoramadak', 'Terrain Response'],
      description: 'Luxe en performance in perfecte harmonie. De ultieme SUV voor de veeleisende rijder.',
    },
    {
      id: 'porsche-911',
      make: 'Porsche',
      model: '911 Carrera S',
      year: 2024,
      price: 149800,
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?auto=format&fit=crop&w=1200',
      ],
      type: 'sports' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Benzine' as const,
      color: 'Guards Red',
      doors: 2,
      seats: 4,
      power: '450 PK',
      features: ['Sport Chrono', 'PASM', 'Sport Exhaust', 'Bose Audio', 'Sport Seats Plus', 'LED Matrix Headlights'],
      description: 'De iconische sportwagen. Legendarische Porsche engineering in zijn puurste vorm.',
    },
    {
      id: 'mercedes-eqs',
      make: 'Mercedes-Benz',
      model: 'EQS 450+',
      year: 2024,
      price: 118500,
      image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1200',
      ],
      type: 'luxury' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Elektrisch' as const,
      color: 'Zilver Metallic',
      doors: 4,
      seats: 5,
      power: '333 PK',
      features: ['MBUX Hyperscreen', 'Airmatic Suspension', 'Burmester 3D Audio', 'Augmented Reality Navigation', '725 km bereik', 'Massage Seats'],
      description: 'Elektrische luxe geherdefinieerd. Het summum van comfort en innovatie.',
    },
    {
      id: 'audi-rs6',
      make: 'Audi',
      model: 'RS6 Avant',
      year: 2023,
      price: 142900,
      image: 'https://images.unsplash.com/photo-1610768764270-790fbec18178?auto=format&fit=crop&w=1200',
      images: [
        'https://images.unsplash.com/photo-1610768764270-790fbec18178?auto=format&fit=crop&w=1200',
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200',
      ],
      type: 'sports' as const,
      condition: 'new' as const,
      mileage: 0,
      transmission: 'Automatic' as const,
      fuelType: 'Benzine' as const,
      color: 'Nardo Grijs',
      doors: 5,
      seats: 5,
      power: '600 PK',
      features: ['Quattro AWD', 'Dynamic Ride Control', 'RS Sport Exhaust', 'Bang & Olufsen 3D Audio', 'Matrix LED Headlights', 'Carbon Ceramic Brakes'],
      description: 'De perfecte combinatie van praktisch en performance. Supersportwagen in stationwagen vorm.',
    },
  ] as Car[],
};
